spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${APP_EMAIL}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload-dir: "./uploads"
  image-types: jpg, jpeg, png

application:
  security:
    secret-key: ${SECRET_KEY}
    token-expiration-time: 36_000_000
  default-admin:
    email: ${ADMIN_EMAIL:app@gmail.com}
    password: ${ADMIN_PASSWORD:admin}
  reservation:
    max-count-per-user: 5
    expiration-in-days: 2
