spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
file:
  upload-dir: "./uploads"
  image-types: jpg, jpeg, png
application:
  secret-key: ${SECRET_KEY}
  token-expiration-time: 36000000
